- .gitignore
- AUTHORS
- Dockerfile
- etc/wazo-agentd/config.yml
- integration_tests/Dockerfile-agentd
- integration_tests/Makefile
- integration_tests/assets/docker-compose.base.override.yml
- integration_tests/assets/docker-compose.yml
- integration_tests/assets/etc/wazo-agentd/conf.d/50-default.yml
- integration_tests/assets/key-file.yml
- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/bus.py
- integration_tests/suite/helpers/database.py
- integration_tests/suite/helpers/fixtures.py
- integration_tests/suite/test_agents.py
- integration_tests/suite/test_agents_by_number.py
- integration_tests/suite/test_documentation.py
- integration_tests/suite/test_event_handler.py
- integration_tests/test-requirements.txt
- setup.cfg
- test-requirements.txt
- tox.ini
- wazo_agentd/bin/agentd.py
- wazo_agentd/bus.py
- wazo_agentd/service/proxy.py
int tests: test when queue is deleting
remove useless queue create handler
use same mechanic as other services for bus event handler
int tests: add framework and test event from login
todo rebase with add docker-compose
int tests: test authentication
AUTHORS: use Wazo Communication Inc.
add framework for integration tests
Dockerfile: fix permissions to certificate
add default consul config
WIP refactor bus
rename amqp module to bus module
add default config to config.py
use pytest instead of deprecated nosetests
> Pull request for WAZO-940-integration-tests-agentd

- Dockerfile
- debian/wazo-agentd.postinst
- debian/wazo-agentd.service
- etc/wazo-agentd/config.yml
- wazo_agentd/bin/agentd.py
since buster /var/run is a now a symlink to /run
> use /run instead of /var/run

- integration_tests/Makefile
Depends-On: https://github.com/wazo-platform/sf-jobs/pull/41
> integration_tests/Makefile: do not pull images

- .gitignore
- etc/wazo-agentd/config.yml
- integration_tests/assets/etc/wazo-agentd/conf.d/50-default.yml
- integration_tests/test-requirements.txt
- setup.cfg
- tox.ini
- wazo_agentd/bin/agentd.py
Depends-on: wazo-platform/xivo-test-helpers#31
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1689
> Pull request for WAZO-1689-auth-http

- integration_tests/suite/helpers/database.py
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/41
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1771
> use linefeatures endpoint_sip_id column

- Dockerfile
- integration_tests/assets/docker-compose.yml
- integration_tests/assets/etc/wazo-agentd/conf.d/50-default.yml
test: add debug true
improve docker image size
> Pull request for improve-docker

- wazo_agentd/swagger/resource.py
resource_string return byte object and we need to cast to dict before
updating it
> fix api reverse proxied

- etc/wazo-agentd/config.yml
- wazo_agentd/config.py
reason: consul is configured to http
> remove irrelevant verify consul option

- Dockerfile
- debian/wazo-agentd.postinst
- debian/wazo-agentd.service
- etc/wazo-agentd/config.yml
- wazo_agentd/config.py
- wazo_agentd/main.py
reason: systemd restart remove monit usage based on pid file
> Pull request for WAZO-1842-remove-pid

- CHANGELOG.md
- integration_tests/assets/docker-compose.base.override.yml
- integration_tests/assets/docker-compose.yml
- integration_tests/assets/etc/wazo-agentd/conf.d/50-default.yml
- integration_tests/suite/helpers/amid.py
- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/bus.py
- integration_tests/suite/test_agents.py
- wazo_agentd/http.py
- wazo_agentd/main.py
- wazo_agentd/service/handler/pause.py
- wazo_agentd/service/handler/status.py
- wazo_agentd/service/manager/pause.py
- wazo_agentd/service/proxy.py
- wazo_agentd/swagger/api.yml
Depends-on: https://github.com/wazo-platform/wazo-agentd-client/pull/10
> Pull request for WAZO-2076-user-pause-resume

- wazo_agentd/http.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/60
reason: when using recurse=True, flask helpers already fetch tenants. So
instead to fetch list twice, we use the same list
> use flask helpers to avoid duplicate requests

- wazo_agentd/bus.py
- wazo_agentd/main.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/30
> bus: use correct policy for publishing

- wazo_agentd/http.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/79
> update handle_unauthorized definition

- integration_tests/suite/helpers/database.py
- wazo_agentd/service/action/login.py
- wazo_agentd/service/action/tests/test_login.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/135
> remove "TODO clean after pjsip migration"

- wazo_agentd/dao.py
- wazo_agentd/exception.py
- wazo_agentd/main.py
- wazo_agentd/service/action/login.py
- wazo_agentd/service/action/logoff.py
- wazo_agentd/service/action/tests/test_login.py
- wazo_agentd/service/action/tests/test_logoff.py
- wazo_agentd/service/manager/blf.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/139
Depends-On: https://github.com/wazo-platform/wazo-auth-keys/pull/54
Depends-On: https://github.com/wazo-platform/xivo-test-helpers/pull/56
> Wazo 2527 agent blf api

- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/bus.py
- integration_tests/suite/test_agents_by_number.py
- wazo_agentd/bus.py
- wazo_agentd/main.py
- wazo_agentd/service/action/login.py
- wazo_agentd/service/action/logoff.py
- wazo_agentd/service/action/tests/test_login.py
- wazo_agentd/service/action/tests/test_logoff.py
- wazo_agentd/service/manager/on_queue_agent_paused.py
- wazo_agentd/service/manager/tests/test_on_agent_paused.py
Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/69
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/47
> WAZO-2496 Inject tenant_uuid in bus events

- requirements.txt
- tox.ini
- wazo_agentd/schemas.py
Depends-On: https://github.com/wazo-platform/xivo-lib-python/pull/93
> Migration of Marshmallow version

- integration_tests/suite/test_agentd_status.py
- integration_tests/suite/test_documentation.py
- wazo_agentd/bus.py
- wazo_agentd/http.py
- wazo_agentd/main.py
- wazo_agentd/swagger/api.yml
Depends-On: https://github.com/wazo-platform/wazo-agentd-client/pull/16
> wazo-agentd: add /status endpoint

- integration_tests/suite/helpers/base.py
- integration_tests/suite/test_agentd_status.py
- integration_tests/suite/test_agents_by_number.py
- wazo_agentd/bus.py
- wazo_agentd/main.py
- wazo_agentd/service/action/login.py
- wazo_agentd/service/action/logoff.py
- wazo_agentd/service/action/tests/test_login.py
- wazo_agentd/service/action/tests/test_logoff.py
- wazo_agentd/service/manager/on_queue_agent_paused.py
- wazo_agentd/service/manager/tests/test_on_agent_paused.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/59
> WAZO-2505: agentd event

- CHANGELOG.md
- etc/wazo-agentd/config.yml
- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/bus.py
- integration_tests/suite/test_agents_by_number.py
- wazo_agentd/bus.py
- wazo_agentd/config.py
Depends-On: https://github.com/wazo-platform/wazo-amid-client/pull/10
> WAZO-3001: `agentd` publish to wazo headers

- wazo_agentd/http.py
> add log before request

- wazo_agentd/swagger/api.yml
depends-on: https://github.com/wazo-platform/wazo-platform.org/pull/613
> [WAZO-3270] Add logo to spec

- integration_tests/test-requirements.txt
- requirements.txt
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/207
> Add dependency on sqlalchemy-utils for dao

- integration_tests/Dockerfile-agentd
https://wazo-dev.atlassian.net/browse/WAZO-3342
> Updated integration test dockerfile editable install command

- wazo_agentd/http.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/140
> use default AuthVerifier instead of custom

- debian/wazo-agentd.dirs
- debian/wazo-agentd.service
- etc/rsyslog.d/99-wazo-agentd.conf
> WAZO-3682: disable logs in rsyslog

- wazo_agentd/http.py
> HTTP server: apply cheroot patch

- integration_tests/suite/helpers/database.py
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/288
> tests: base db template rename

- CHANGELOG.md
- integration_tests/suite/test_agents.py
- wazo_agentd/plugins/agent/api.yml
- wazo_agentd/service/handler/status.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/314
Depends-On: https://github.com/wazo-platform/wazo-agentd-client/pull/27
> Wp 1925 add per queue information

- integration_tests/suite/helpers/database.py
- integration_tests/suite/test_event_handler.py
to actually delete the agent and expect actual consequences
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/317
> integration_tests: fix test_on_agent_deleted
